/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsPack {
  IconsPack._();

  static const _kFontFam = 'FlutterIcons';
  static const String? _kFontPkg = null;

  static const IconData favouritefilled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favouritelineal = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickrfilled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickrlineal = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData followerfilled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData followerlineal = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData foursquarefilled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData foursquarelineal = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendsfilled = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendslineal = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData giffilled = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData giflineal = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleplusfilled = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlepluslineal = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hashtagfilled = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hashtaglineal = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homefilled = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homelineal = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imagefilled = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imagelineal = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagramfilled = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagramlineal = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like2filled = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like2lineal = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData likefilled = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData likelineal = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linefilled = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linelineal = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedinfilled = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedinlineal = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationpinfilled = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationpinlineal = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messagefilled = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messagelineal = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messengerfilled = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messengerlineal = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newsfeedfilled = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newsfeedlineal = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationfilled = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationlineal = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterestfilled = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterestlineal = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pollfilled = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polllineal = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redditfilled = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redditlineal = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sharefilled = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sharelineal = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skypefilled = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skypelineal = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchatfilled = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchatlineal = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotifyfilled = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotifylineal = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storiesfilled = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storieslineal = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swarmfilled = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swarmlineal = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tagfilled = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taglineal = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegramfilled = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegramlineal = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tiktokfilled = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tiktoklineal = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trendingfilled = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trendinglineal = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblrfilled = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblrlineal = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitchfilled = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitchlineal = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitterfilled = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitterlineal = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userfilled = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userlineal = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verifiedfilled = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verifiedlineal = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viberfilled = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viberlineal = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wechatfilled = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wechatlineal = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsappfilled = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapplineal = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtubefilled = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtubelineal = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addfilled = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addfriendfilled = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addfriendlineal = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addlineal = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commentfilled = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commentlineal = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deviantartfilled = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deviantartlineal = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislikefilled = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislikelineal = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbblefilled = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbblelineal = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emojifilled = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emojilineal = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebookfilled = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebooklineal = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);


}
